import { parseAbi } from "viem";

/** The slice of BasketVault the agent talks to. Mirrors packages/foundry/contracts/BasketVault.sol. */
export const vaultAbi = parseAbi([
  "function owner() view returns (address)",
  "function shareToken() view returns (address)",
  "function nav() view returns (uint256)",
  "function navUsd() view returns (uint256)",
  "function hbarUsd() view returns (uint256)",
  "function holdings() view returns ((address token, uint256 balance, uint256 valueWhbar, uint16 targetBps)[])",
  "function legs() view returns ((address token, address pool, uint24 fee, bool tokenIsToken0, uint16 weightBps)[])",
  "function rebalanceInterval() view returns (uint256)",
  "function pendingSchedule() view returns (address)",
  "function nextRunAt() view returns (uint256)",
  "function scheduledGas() view returns (uint256)",
  "function driftBps() view returns (uint256)",
  "function maxDeviationBps() view returns (uint256)",
  "function guardLeg() view returns (uint256)",
  "function DEAD_SHARES() view returns (uint256)",
  "function deposit(uint256 minShares) payable returns (uint256 shares)",
  "function redeem(uint256 shares) returns (uint256 whbarOut, uint256[] legAmounts)",
  "function redeemExcept(uint256 shares, uint256 skipLegsMask) returns (uint256 whbarOut, uint256[] legAmounts)",
  "function rebalance() returns (bool traded)",
  "function rearm()",
  "event Deposited(address indexed account, uint256 hbarIn, uint256 valueAdded, uint256 shares)",
  "event Redeemed(address indexed account, uint256 shares, uint256 whbarOut, uint256[] legAmounts)",
  "event LegsSkipped(address indexed account, uint256 skipLegsMask)",
  "event Rebalanced(uint256 navBefore, uint256 navAfter, bool traded)",
  "event RunBooked(address indexed schedule, uint256 expiry)",
  "event BookingFailed(int64 responseCode)",
  "error AlreadyInitialized()",
  "error NotInitialized()",
  "error ZeroAmount()",
  "error InsufficientShares(uint256 shares, uint256 minShares)",
  "error StaleOracle(uint256 updatedAt)",
  "error BadOraclePrice(int256 answer)",
  "error PoolPriceDeviates(uint256 poolHbarUsd, uint256 oracleHbarUsd)",
  "error HtsCallFailed(int64 responseCode)",
  "error TransferFailed(address token)",
  "error OnlyOwnerOrSelf()",
  "error NotAutomated()",
  "error RunAlreadyPending(address schedule)",
  "error BadSkipMask(uint256 skipLegsMask)",
  "error ScheduleFailed(int64 responseCode)",
]);

export const erc20Abi = parseAbi([
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
]);
